name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Setup Google Cloud SDK"
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: "latest"
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: "Create credentials file"
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json

      - name: "Terraform Init"
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Terraform Apply"
        run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "bucket_name=${{ secrets.GCP_PROJECT_ID }}-tfstate" -var "credentials_file=credentials.json"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
